- name: TypeScript
  logo: typescript
  url: https://www.typescriptlang.org
  logoColor: FFFFFF
  color: 007ACC
  projects:
    - url: https://github.com/Standard-Structure/struct
      wip: true
    - https://github.com/cjdenio/hackclub-ship
    - url: https://github.com/cjdenio/frcbot-2.0
      wip: true
- name: JavaScript
  logo: javascript
  logoColor: FFFFFF
  color: F7DF1E
  url: https://nodejs.org
  projects:
    - https://github.com/deniosoftware/trello-display
- name: Go
  logo: go
  url: https://golang.org
  logoColor: FFFFFF
  color: 00ADD8
  projects:
    - https://github.com/cjdenio/birthdaybot
    - url: https://github.com/cjdenio/upload-scheduler
      wip: true
- name: Vue.js
  logo: vue.js
  url: https://vuejs.org
  logoColor: FFFFFF
  color: 4FC08D
  projects:
    - https://github.com/deniosoftware/trello-display
    - url: https://github.com/cjdenio/upload-scheduler
      wip: true
    - url: https://github.com/cjdenio/reminder-app
      wip: true
- name: Docker
  logo: docker
  url: https://www.docker.com
  logoColor: FFFFFF
  color: 2496ED
  projects:
    - https://github.com/cjdenio/birthdaybot
    - url: https://github.com/cjdenio/upload-scheduler
      wip: true
    - url: https://github.com/deniosoftware/frcbot-2.0
      wip: true
    - url: https://github.com/cjdenio/contributor_list
      wip: true
- name: Python
  logo: python
  url: https://python.org
  logoColor: FFFFFF
  color: 3776AB
  projects:
    - url: https://github.com/cjdenio/contributor_list
      wip: true
